import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Toaster } from 'sonner';

import { cn } from '@/lib/utils';

import './globals.css';
import { QueryProvider } from './provider';

const inter = Inter({
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Jira',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className={cn(inter.className, 'antialiased min-h-screen')}>
                <NuqsAdapter>
                    <QueryProvider>
                        <Toaster />
                        {children}
                    </QueryProvider>
                </NuqsAdapter>
            </body>
        </html>
    );
};